[package]
name = "quadB"
version = "0.1.0"
edition = "2021"

[dependencies]


[[bin]]
name = "palindrome"
path = "src/bin/palindrome.rs"

[[bin]]
name = "binsearch"
path = "src/bin/binary_search.rs"

[[bin]]
name = "shortestword"
path = "src/bin/shortest_word.rs"